// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEWInd1wz4pYvQkLPX6gvqQuBAR3QVkwU',
    appId: '1:76849100825:web:60eb8349b52ba688ed9288',
    messagingSenderId: '76849100825',
    projectId: 'massarbus-e8b25',
    authDomain: 'massarbus-e8b25.firebaseapp.com',
    storageBucket: 'massarbus-e8b25.firebasestorage.app',
    measurementId: 'G-PF9PNGQ2TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO8YQczJUJKJROEZ9pXkxrgLjSoHjqSts',
    appId: '1:76849100825:android:3cf844da23466570ed9288',
    messagingSenderId: '76849100825',
    projectId: 'massarbus-e8b25',
    storageBucket: 'massarbus-e8b25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAseXd-1sPAZ4i0CQBpL6kHxKq5Zl2qimg',
    appId: '1:76849100825:ios:3c3d3d6990157ed6ed9288',
    messagingSenderId: '76849100825',
    projectId: 'massarbus-e8b25',
    storageBucket: 'massarbus-e8b25.firebasestorage.app',
    iosBundleId: 'com.example.massarbusParent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAseXd-1sPAZ4i0CQBpL6kHxKq5Zl2qimg',
    appId: '1:76849100825:ios:3c3d3d6990157ed6ed9288',
    messagingSenderId: '76849100825',
    projectId: 'massarbus-e8b25',
    storageBucket: 'massarbus-e8b25.firebasestorage.app',
    iosBundleId: 'com.example.massarbusParent',
  );
}
